org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
jei_version=15.20.0.112
emi_version=1.1.21+1.20.1
rei_version=12.1.785
curios_version=5.12.1+1.20.1

gtceu_version=7.2.0
ldlib_version=1.0.40.b

mapping_channel=official
mapping_version=1.20.1

mod_id=expandedae
mod_name=Expanded AE
mod_license=GNU Lesser General Public License v3.0
mod_version=1.4.1.b
mod_group_id=lu.kolja
mod_authors=Kolja
mod_description=Bigger pattern provider and more QoL features

recipemanager_mod=emi

neoForge.parchment.minecraftVersion=1.20.1
neoForge.parchment.mappingsVersion=2023.09.03
